name: test
on:
  push
jobs:
  automated-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - name: run commands
        run: |
          #node ./m3u-checker.js test_input/ test_output/ --quiet
          while read id ; do echo "Processing ID: $id" ; curl -s "https://retunefm.com/radio/$id/" > mep1 ; title=$(htmlq h1 -t < mep1 | sed 's/ — listen online//') ; stream=$(grep -oP '(?<=;stream&quot;:&quot;)[^&]*' mep1 | head -n1) ; grep -oP '(Country|Language|Genres)</td><td[^>]*>\K[^<]+' mep1 | while read value ; do echo "$value" | tr ',' '\n' | sed 's/^ *// ; s/ *$// ; s/ /_/g ; s/[^a-zA-Z0-9_]/_/g' | while read val ; do [ -n "$val" ] && (echo "#EXTINF:-1,$title" >> "$val.m3u" ; echo "$stream" >> "$val.m3u") ; done ; done ; done < list.txt
          rm mep1

      - name: git stuff
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "$(od -An -tx4 -w16 -N16 /dev/urandom | cut -c2- | tr '[:lower:]' '[:upper:]')"
          git push
